baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

blog  = "blog/:slug/"

[[menu.main]]
name               	= "Kontakt"
weight             	= -210
identifier         	= "kontakt"
url                	= "/kontakt"

[[menu.main]]
name               	= "Om"
weight             	= -200
identifier         	= "om"
url                	= "/om"

[[menu.main]]
name               	= "Home"
weight             	= -220
identifier         	= "home"
url                	= "/"

[[menu.main]]
name               	= "Blog"
weight             	= -190
identifier         	= "blog"
url                	= "/blog/"

[[menu.main]]
name               	= "Portfolio"
weight             	= -180
identifier         	= "portfolio"
url                	= "/portfolio/"
[params]
extracssfiles          = [ "/css/override.css" ]
